CREATE OR REPLACE PROCEDURE SP_AUTOGES_PERFILES_Y_ROLES
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_IN_CEDULA_EPL IN EMPLEADOS_BASIC.COD_EPL%TYPE,  -- CEDULA DEL EMPLEADO
	V_OUT_MENU OUT SYS_REFCURSOR,					  -- ITEMS DEL MENU QUE TENDRA HABILITADO EL EMPLEADO A CORDE A SU ROL 
	V_OUT_SUBMENU OUT SYS_REFCURSOR,				  -- ITEMS DEL SUBMENU QUE TENDRA HABILITADO EL EMPLEADOS A CORDE A SU ROL
	V_OUT_MENSAJE OUT VARCHAR2,						  -- MENSAJE DE CARGA O ERROR
	V_OUT_CODIGO_MENSAJE OUT NUMBER					  -- CODIGO DE MENSAJE (0 CORRECTO, -20001 CEDULA NO EXISTENTE)
)
AS
	ROL_PREDETERMINADO VARCHAR2(10); -- VARIABLE QUE CONTIENE EL ROL PREDETERMINADO DEL EMPLEADO
	ROL_ESPECIAL VARCHAR2(20);		 -- VARIABLE QUE CONTIENE EL ROL ESPECIAL ASIGNADO
	EXISTE_CEDULA NUMBER;			 -- VARIABLE QUE CONTIENE LA CANTIDAD DE REGISTROS EN EMPLEADOS BASIC CON LA CEDULA 
	MENU_IN_SYS SYS_REFCURSOR;
	SUBMENU_IN_SYS SYS_REFCURSOR;
BEGIN
	-- COMPRUEBA QUE LA CEDULA SI EXISTA Y PERTENECE A UN EMPLEADO
	SELECT COUNT(*)
	INTO EXISTE_CEDULA
	FROM EMPLEADOS_BASIC EB
	WHERE EB.CEDULA = V_IN_CEDULA_EPL;

	-- SI LA CEDULA ESXISE REALIZA LA RESPECTIVA ACCION SI NO ES NOTIFICADO
	IF(EXISTE_CEDULA >= 1) THEN
		BEGIN
			-- IDENTIFICAR SI TINE UN ROL ESPECIAL ASIGNADO
			ROL_ESPECIAL := PKG_AUTOGES_ROLES_Y_PERFILES.FN_IDENTIF_ROL_ESPECIAL(V_IN_CEDULA_EPL);

			-- SI TIENE UN ROL ESPECIAL ASIGNADO SE CONSULTA LOS ITEM QUE TIENE SELECCIONADO DEL MENU Y SE RETORNAN EN LA VARIABLE DE SALIDA
			-- DE LO CONTRARIO SE MIRA A QUE ROL PREDETERMINADO ESTA ASIGNADO Y SE MIRA SUS ITEM CORRESPONDIENTES
			CASE ROL_ESPECIAL
				WHEN 'ESPECIAL' THEN
					BEGIN
						-- ITEMS DEL MENU QUE TIENE ASIGNADO EL ROL ESPECIAL ASIGNADO AL EMPLEADO
						PKG_AUTOGES_ROLES_Y_PERFILES.SP_AUTOGES_MENUITEM_ESPECIAL(V_IN_CEDULA_EPL,MENU_IN_SYS);
						V_OUT_MENU := MENU_IN_SYS;

						-- ITEMS DEL SUBMENU QUE TIENE ASIGNADOS EL ROL ESPECUAL ASIGNADO AL EMPLEADO
						PKG_AUTOGES_ROLES_Y_PERFILES.SP_AUTOGES_SUBMENUITEM_SPECIAL(V_IN_CEDULA_EPL,SUBMENU_IN_SYS);
						V_OUT_SUBMENU := SUBMENU_IN_SYS;

						-- MENSAJE DE ACCION COMPLETADA
						V_OUT_MENSAJE := 'Menus y submenus cargados al rol perteneciente';

						V_OUT_CODIGO_MENSAJE := 0;
					END;
				WHEN 'SIN_ROL' THEN 
					BEGIN
						-- IDENTIFICAR EL ROL PREDETEMRINADO QUE TIENE ASIGNADO
						ROL_PREDETERMINADO := PKG_AUTOGES_ROLES_Y_PERFILES.FN_IDENTIF_ROL_PREDETERMINADO(V_IN_CEDULA_EPL);

						-- ITEMS DEL MENU QUE TIENE ASIGNADO EL ROL ESPECIAL ASIGNADO AL EMPLEADO
						PKG_AUTOGES_ROLES_Y_PERFILES.SP_AUTOGES_MENUITEM_PREDETERM(ROL_PREDETERMINADO,MENU_IN_SYS);
						V_OUT_MENU := MENU_IN_SYS;

						-- ITEMS DEL SUBMENU QUE TIENE ASIGNADOS EL ROL ESPECUAL ASIGNADO AL EMPLEADO
						PKG_AUTOGES_ROLES_Y_PERFILES.SP_AUTOGES_SUBMENUITEM_PREDETE(ROL_PREDETERMINADO,SUBMENU_IN_SYS);
						V_OUT_SUBMENU := SUBMENU_IN_SYS;

						-- MENSAJE DE ACCION COMPLETADA
						V_OUT_MENSAJE := 'Menus y submenus cargados al rol perteneciente';

						V_OUT_CODIGO_MENSAJE := 0;
					END;
			END CASE;
		END;

	ELSE

		BEGIN
			-- RETORNAMOS TODO LOS ITEMS DEL MENU FALSOS
			OPEN V_OUT_MENU FOR
				SELECT COD_MENU MENU,
				    NOM_MENU,
				    'FALSE' VALOR
				FROM T_MENU;

			-- RETORNAMOS TODOS LOS ITEMS DEL SUBMENU FALSOS
			OPEN V_OUT_SUBMENU FOR
				SELECT COD_SUB_MENU MENU,
				    NOM_SUB_MENU,
				    'FALSE' VALOR
				FROM T_SUB_MENU;

			V_OUT_MENSAJE := 'La cedula ingresada no pertenece a ningun empleado registrado.';

			V_OUT_CODIGO_MENSAJE := -20001;
		END;
	END IF;
END;