create or replace PROCEDURE TW_PC_EQUIPO_NOMINA
/********************OBJETIVO: INFORMACION DEL EQUIPO DE NOMINA *******************************
CREADO POR       : NELSON GALEANO
   
--PARAMETROS DE SALIDA   
  -- BLOQUE 1 => JEFE
  -- BLOQUE 2 => PROFESIONALES
  -- BLOQUE 3 => ANALISTAS
  -- BLOQUE 4 => ESTUDIANTES
  -- BLOQUE 5 => OBJETIVOS
  -- BLOQUE 6 => RETOS
  -- BLOQUE 7 => IMPORTANCIA
  -- IMPORTANCIA
************************************  DECLARACION DE VARIABLE  ************************************************************ */
(
    BLOQUE1     OUT SYS_REFCURSOR,    
    BLOQUE2     OUT SYS_REFCURSOR,    
    BLOQUE3     OUT SYS_REFCURSOR, 
    BLOQUE4     OUT SYS_REFCURSOR,    
    BLOQUE5     OUT SYS_REFCURSOR,
    BLOQUE6     OUT SYS_REFCURSOR,
    BLOQUE7     OUT SYS_REFCURSOR    
)
IS
BEGIN
    -- JEFE DE NOMINA
    OPEN BLOQUE1 FOR
    SELECT TN.NOM_TITULO, TD.DECRIPCION 
    FROM TITULOS_EQUI_NOMINA TN, TITULOS_DETALLE TD
    WHERE TN.COD_TITULO = TD.COD_TITULO
    AND TN.COD_TITULO = '1';
    
    -- PROFESIONALES DE NOMINA
    OPEN BLOQUE2 FOR
    SELECT TN.NOM_TITULO, TD.DECRIPCION 
    FROM TITULOS_EQUI_NOMINA TN, TITULOS_DETALLE TD
    WHERE TN.COD_TITULO = TD.COD_TITULO
    AND TN.COD_TITULO = '2';
    
    -- ANALISTAS DE NOMINA
    OPEN BLOQUE3 FOR
    SELECT TN.NOM_TITULO, TD.DECRIPCION 
    FROM TITULOS_EQUI_NOMINA TN, TITULOS_DETALLE TD
    WHERE TN.COD_TITULO = TD.COD_TITULO
    AND TN.COD_TITULO = '3';    
    
    -- ESTUDIANTES
    OPEN BLOQUE4 FOR
    SELECT TN.NOM_TITULO, TD.DECRIPCION 
    FROM TITULOS_EQUI_NOMINA TN, TITULOS_DETALLE TD
    WHERE TN.COD_TITULO = TD.COD_TITULO
    AND TN.COD_TITULO = '4';    
    
    -- OBJETIVO
    OPEN BLOQUE5 FOR
    SELECT TN.NOM_TITULO, TD.DECRIPCION 
    FROM TITULOS_EQUI_NOMINA TN, TITULOS_DETALLE TD
    WHERE TN.COD_TITULO = TD.COD_TITULO
    AND TN.COD_TITULO = '5';
    
    -- RETOS
    OPEN BLOQUE6 FOR
    SELECT TN.NOM_TITULO, TD.DECRIPCION 
    FROM TITULOS_EQUI_NOMINA TN, TITULOS_DETALLE TD
    WHERE TN.COD_TITULO = TD.COD_TITULO
    AND TN.COD_TITULO = '6';
    
    -- IMPORTANCIA
    OPEN BLOQUE7 FOR
    SELECT TN.NOM_TITULO, TD.DECRIPCION 
    FROM TITULOS_EQUI_NOMINA TN, TITULOS_DETALLE TD
    WHERE TN.COD_TITULO = TD.COD_TITULO
    AND TN.COD_TITULO = '7';       
END TW_PC_EQUIPO_NOMINA;