CREATE OR REPLACE PACKAGE PKG_AUTOGES_ROLES_Y_PERFILES
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS
	--FUNCION IDENTIFICAR QUE ROL ESPECUAL TIENE UN USUARIO
	FUNCTION FN_IDENTIF_ROL_ESPECIAL
	(
		V_CEDULA_EPL EMPLEADOS_BASIC.CEDULA%TYPE -- CEDULA DEL EMPLEADO A IDENTIFICAR ROL 
	)
	RETURN VARCHAR2;

	-- FUNCION IDENTIFICAR QUE ROL PREDETERMINADO TIENE ASIGNADO
	FUNCTION FN_IDENTIF_ROL_PREDETERMINADO
	(
		V_CEDULA_EPL EMPLEADOS_BASIC.CEDULA%TYPE -- CEDULA DEL EMPLEADOA IDENTIFICAR ROL
	)
	RETURN VARCHAR2;

	-- ASIGNA UN ROL ESPECIAL A UN EMPLEADO
	PROCEDURE SP_AUTOGES_ASIGNAR_ROLESPACIAL
	(
		V_IN_CEDULA_EMPLEADO IN EMPLEADOS_BASIC.CEDULA%TYPE,          -- CEDULA DEL EMPLEADO AL QUE SE LE ASIGNA UN ROL ESPECUAL
		V_IN_COD_ROLESPECIAL IN T_ROL_ESPECIAL.COD_ROL_ESPECIAL%TYPE, -- CODIGO DEL ROL ESPECIAL QUE SE LE VA ASIGNAR 
		V_OUT_MENSAJE OUT VARCHAR2									  -- MENSAJE DE ACCION
	);

	-- CREA UN ROL ESPECIAL
	PROCEDURE SP_AUTOGES_CREAR_ROLESPECIAL
	(
		V_IN_NOMBRE_ROL IN VARCHAR2,  -- NOMBRE DEL ROL ESPECIAL A CREAR
		V_IN_DESCRIPCION IN VARCHAR2, -- DESCRIPCION DEL ROL
		V_IN_SUBMENUS IN VARCHAR2, 	  -- SUBMENUS ASIGANADAS AL ROL QUE SE CREA
		V_OUT_MENSAJE OUT VARCHAR2	  -- MENSAJE DE LA ACCION OCURRIDA
	);

	-- MUESTRA LOS ROLES ESPECIALES CREADOS CON LOS SUBMENUS ASIGNADOS
	PROCEDURE SP_AUTOGES_DETALLE_ROLESPECIAL
	(
		V_OUT_ROLES_SUBMENUS OUT SYS_REFCURSOR	-- DATOS DE LOS ROLES ESPECIALES
	);

	-- ITEMS ASIGNADOS AL ROL ESPECIAL QUE TIENE ASIGNADO EL EMPLEADO
	PROCEDURE SP_AUTOGES_MENUITEM_ESPECIAL
	(
		V_IN_CEDULA_EPL IN EMPLEADOS_BASIC.COD_EPL%TYPE, -- CEDULA DEL EMPLEADO CON ROL ESPECUAL
		V_OUT_MENU OUT SYS_REFCURSOR					 -- ITEMS ASIGNADOS
	);

	-- ITEMS ASIGNADOS AL ROL PREDETERMINADO QUE TENGA ASIGNADO UN EMPLEADO
	PROCEDURE SP_AUTOGES_MENUITEM_PREDETERM
	(
		V_IN_ROL_EPL IN VARCHAR2,		-- CODIGO DEL ROL PREDETERMINADO QUE TIENE ASIGNAFO
		V_OUT_MENU OUT SYS_REFCURSOR	-- ITEMS ASIGNADOS 
	);

	-- SUBITEMS ASIGNADOS AL ROL PREDETERMINADO QUE TIENE ASIGNADO UN EMPLEADO
	PROCEDURE SP_AUTOGES_SUBMENUITEM_PREDETE
	(
		V_IN_ROL_EPL IN VARCHAR2,		 -- CODIGO DEL ROL 
		V_OUT_SUBMENU OUT SYS_REFCURSOR	 -- SUBITEMS ASIGNADOS
	);

	-- SUBITEMS ASIGNADOS AL ROL ESPECUAL QUE TIENE ASIGNADO UN EMPLEADO
	PROCEDURE SP_AUTOGES_SUBMENUITEM_SPECIAL
	(
		V_IN_CEDULA_EPL IN EMPLEADOS_BASIC.COD_EPL%TYPE,
		V_OUT_SUBMENU OUT SYS_REFCURSOR
	);

	-- SUBITEMS QUE SE LE ASIGNAN A UN ROL ESPECIAL CREADO 
	PROCEDURE SP_AUTOGES_SUBMENUS_ASIGNADOS
	(
		V_IN_DATOS IN VARCHAR2,		    	  -- VARIABLE QUE CONTIENE TODOS LOS DATOS INSERTADOS SEPARADOS POR COMAS
		ARRAY_DATOS OUT ARRAY_DE_DATOS_TYPE,  -- CODIGOS DE LOS SUBITEMS QUE SE LE ASIGNANA AL ROL ESPECUAL CREADO
		V_OUT_NUM_DATOS  OUT NUMBER			  -- NUMERO DE SUBITEMS ASIGNADOS AL ROL ESPECIAL
	);
END;