DROP TABLE TELEPRU.T_RELACION_MENU_ROL CASCADE CONSTRAINTS;

CREATE TABLE TELEPRU.T_RELACION_MENU_ROL
(
  COD_ROL       NUMBER,
  COD_SUB_MENU  NUMBER                          NOT NULL
)
TABLESPACE TELEFONICA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM T_RELACION_MENU_ROL FOR TELEPRU.T_RELACION_MENU_ROL;


ALTER TABLE TELEPRU.T_RELACION_MENU_ROL ADD (
  FOREIGN KEY (COD_ROL) 
  REFERENCES TELEPRU.T_ROLES (COD_ROL)
  ENABLE VALIDATE,
  FOREIGN KEY (COD_SUB_MENU) 
  REFERENCES TELEPRU.T_SUB_MENU (COD_SUB_MENU)
  ENABLE VALIDATE);
