ALTER TABLE TELEPRU.T_ROL_ESPECIAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE TELEPRU.T_ROL_ESPECIAL CASCADE CONSTRAINTS;

CREATE TABLE TELEPRU.T_ROL_ESPECIAL
(
  COD_ROL_ESPECIAL  NUMBER                      NOT NULL,
  NOM_ROL_ESPECIAL  VARCHAR2(100 BYTE)          NOT NULL,
  DESCRIPCION       VARCHAR2(200 BYTE)
)
TABLESPACE TELEFONICA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index TELEPRU.SYS_C0015736.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER TELEPRU.TRG_ROL_ESPECIAL 
BEFORE INSERT ON TELEPRU.T_ROL_ESPECIAL 
FOR EACH ROW
BEGIN
  SELECT COD_ROL_ESPC_SEQ.NEXTVAL
  INTO   :NEW.COD_ROL_ESPECIAL
  FROM   DUAL;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM T_ROL_ESPECIAL FOR TELEPRU.T_ROL_ESPECIAL;


ALTER TABLE TELEPRU.T_ROL_ESPECIAL ADD (
  PRIMARY KEY
  (COD_ROL_ESPECIAL)
  USING INDEX
    TABLESPACE TELEFONICA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
