ALTER TABLE TELEPRU.T_SUB_MENU
 DROP PRIMARY KEY CASCADE;

DROP TABLE TELEPRU.T_SUB_MENU CASCADE CONSTRAINTS;

CREATE TABLE TELEPRU.T_SUB_MENU
(
  COD_SUB_MENU  NUMBER                          NOT NULL,
  NOM_SUB_MENU  VARCHAR2(100 BYTE)              NOT NULL,
  COD_MENU      NUMBER,
  DESCRIPCION   VARCHAR2(200 BYTE)
)
TABLESPACE TELEFONICA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index TELEPRU.SYS_C0015730.
--  The object is created when the parent object is created.

CREATE OR REPLACE PUBLIC SYNONYM T_SUB_MENU FOR TELEPRU.T_SUB_MENU;


ALTER TABLE TELEPRU.T_SUB_MENU ADD (
  PRIMARY KEY
  (COD_SUB_MENU)
  USING INDEX
    TABLESPACE TELEFONICA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE TELEPRU.T_SUB_MENU ADD (
  FOREIGN KEY (COD_MENU) 
  REFERENCES TELEPRU.T_MENU (COD_MENU)
  ENABLE VALIDATE);
