DROP TABLE TELEPRU.T_USUARIO_ROL_ESPECIAL CASCADE CONSTRAINTS;

CREATE TABLE TELEPRU.T_USUARIO_ROL_ESPECIAL
(
  COD_USUARIO_ESPECIAL  VARCHAR2(12 BYTE)       NOT NULL,
  COD_ROL_ESPECIAL      NUMBER
)
TABLESPACE TELEFONICA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM T_USUARIO_ROL_ESPECIAL FOR TELEPRU.T_USUARIO_ROL_ESPECIAL;


ALTER TABLE TELEPRU.T_USUARIO_ROL_ESPECIAL ADD (
  FOREIGN KEY (COD_ROL_ESPECIAL) 
  REFERENCES TELEPRU.T_ROL_ESPECIAL (COD_ROL_ESPECIAL)
  ENABLE VALIDATE);
